First version
Stradalec/5CSharpRepository pull request #1
Opened 2024-03-05 03:07 UTC by Stradalec

2024-03-05 11:11 UTC, iredb requested changes

2024-03-05 11:11 UTC, iredb commented on Lab5/Cringe.cs
> +      foreach (string filename in directory) {
в лекции, соответствующей данной лабе был итератор. можешь сделать через него?

2024-03-05 11:11 UTC, iredb commented on Lab5/Cringe.cs
> +    string[] directory;
а где модификаторы доступа🤨

2024-03-06 11:02 UTC, Stradalec commented on Lab5/Cringe.cs
> +    string[] directory;
Всё будет. Но чуть позже

2024-03-06 11:02 UTC, Stradalec commented on Lab5/Cringe.cs
> +      foreach (string filename in directory) {
Не могу, т.к. либо не совсем понял, как работает + у меня skill issue

2024-03-06 16:28 UTC, iredb commented on Lab5/Cringe.cs
> +      foreach (string filename in directory) {
люблю самоиронию.

2024-03-06 16:51 UTC, iredb requested changes

2024-03-06 16:51 UTC, iredb commented on Lab5/Cringe.cs
> +    private string[] directory;
![image](https://github.com/Stradalec/5CSharpRepository/assets/120615742/f6ee0cd4-6a94-45b4-855a-963649f6fff6)

2024-03-06 16:51 UTC, iredb commented on Lab5/Cringe.cs
> +    private string[] directory;
*аналогично для всех подобных случаев*

2024-03-07 00:57 UTC, Stradalec commented on Lab5/Cringe.cs
> +    private string[] directory;
Запрашиваю пояснительную когорту

2024-03-07 02:38 UTC, Stradalec commented on Lab5/Cringe.cs
> +    private string[] directory;
Так и не понял, как должен был исправить, остаётся надеяться на интуицию и телепатию

2024-03-08 00:29 UTC, iredb approved these changes

2024-03-08 00:29 UTC, merged